apiVersion: v1
kind: Namespace
metadata:
  name: yaobank
  labels:
    calico-networking: enabled

---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: yaobank
spec:
  ports:
    - port: 2379
  selector:
    app: database

---
# Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: yaobank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: calico/yaobank-database:multiarch
          command: ["etcd"]
          args:
            - "-advertise-client-urls"
            - "http://database:2379"
            - "-listen-client-urls"
            - "http://0.0.0.0:2379"
          ports:
            - containerPort: 2379
      nodeSelector:
        node: node2

---
# Summary Service
apiVersion: v1
kind: Service
metadata:
  name: summary
  namespace: yaobank
spec:
  ports:
    - port: 80
  selector:
    app: summary

---
# Summary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary
  namespace: yaobank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summary
  template:
    metadata:
      labels:
        app: summary
    spec:
      containers:
        - name: summary
          image: calico/yaobank-summary:multiarch
          ports:
            - containerPort: 80

---
# Customer Service
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: yaobank
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30180
  selector:
    app: customer

---
# Customer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: yaobank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: calico/yaobank-customer:multiarch
          ports:
            - containerPort: 80
      nodeSelector:
        node: node1